source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/haawa799/private-podspecs.git'

use_frameworks!

target 'StrokeDrawingView_Example', :exclusive => true do
  pod "StrokeDrawingView"
end

target 'StrokeDrawingView_Tests', :exclusive => true do
  pod "StrokeDrawingView"
  pod 'FBSnapshotTestCase'
end
