source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StrokeDrawingView_Example', :exclusive => true do
  pod "StrokeDrawingView", :path => "../"
end

target 'StrokeDrawingView_Tests', :exclusive => true do
  pod "StrokeDrawingView", :path => "../"
  pod 'FBSnapshotTestCase'
end
